# Generated by Django 5.1.6 on 2025-09-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_analyser', '0006_sector_stock_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='searches',
            field=models.ManyToManyField(blank=True, related_name='users', to='news_analyser.keyword'),
        ),
    ]
