# Generated by Django 5.1.6 on 2025-11-19 12:27

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_analyser', '0007_alter_userprofile_searches'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={'ordering': ['-create_date']},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date'], 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['symbol']},
        ),
        migrations.AddField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='mentioned_tickers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='news',
            name='raw_gemini_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='news',
            name='sentiment_confidence',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='sentiment_explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='news',
            name='impact_rating',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='name',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='id_name',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='stocks',
            field=models.ManyToManyField(blank=True, related_name='users', to='news_analyser.stock'),
        ),
        migrations.AddIndex(
            model_name='keyword',
            index=models.Index(fields=['name', 'create_date'], name='news_analys_name_3a78f5_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['keyword', 'date'], name='news_analys_keyword_730e16_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['impact_rating'], name='news_analys_impact__e0e41c_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['-date'], name='news_analys_date_387302_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['source', 'date'], name='news_analys_source__06eaab_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['symbol'], name='news_analys_symbol_37fbc0_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['sector', 'symbol'], name='news_analys_sector__3726bf_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user'], name='news_analys_user_id_7e8eea_idx'),
        ),
    ]
