# Generated by Django 5.1.6 on 2025-11-19 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_analyser', '0008_alter_keyword_options_alter_news_options_and_more'),
    ]

    operations = [
    ]
