# Generated by Django 5.1.6 on 2025-11-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_analyser", "0009_remove_duplicate_links"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="link",
            field=models.CharField(db_index=True, max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(max_length=500),
        ),
    ]
